# Generated by Django 3.2.13 on 2022-07-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntdemo', '0002_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='caption',
        ),
    ]
