# Generated by Django 3.2.13 on 2022-07-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdemo', '0003_auto_20220726_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='caption',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
