# Generated by Django 3.2.13 on 2022-07-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntdemo', '0004_uploadimage_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageNT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
